version: '3.8'
services:
  postgres:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    networks:
      - mynetwork

  backend:
    build:  #zipe td q esta no backend
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    environment:
      DATABASE_URL: postgresql://user:password@postgres/mydatabase
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - mynetwork

  frontend:

  networks:
    mynetwork:

volumes: # docker cv vai poder enxergar esse path e criar um arquivo aqui
  postgres_data